# This is a basic workflow to help you get started with Actions

name: Pascal

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pascal:
    name: Run Pascal script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/pascal-action@v1.0.0
        id: pascal
        with:
          path: './ackermann.pas 3 12'
      - name: Print result
        run: echo "${{ steps.pascal.outputs.result }}"
